version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ..:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ..:/data
    ports:
      - "27017:27017"
